Client man
cadia-lvl/WebRICE pull request #36
Opened 2020-11-13 14:54 UTC by SunnevaThorsteins

Stores and retrives the playback rate in an IndexedDB. The ClientStoreManager is a new async class containing the communication with the indexed DB. A few functions where also added to the speedButton class and a few lines in reader.

2020-11-16 16:00 UTC, judyfong requested changes
The ClientStoreManager code looks good. I'm glad you've implemented this. However, on a page refresh the cli changes are updated only in SpeedButton's ui, never not in the player itself. I've made some suggestions of how to propagate the changes back to the player.

2020-11-23 14:44 UTC, SunnevaThorsteins commented
I have added the suggested changes to the Speed button. I also decided to disable the linebreak-style in the eslintrc since I do no think it is of much use and causes a lot of unnecessary errors.

2020-11-23 15:47 UTC, judyfong approved these changes

2020-11-23 15:47 UTC, judyfong commented
Looks good to merge.

2020-11-23 15:48 UTC, merged