Keyboard Interface
cadia-lvl/WebRICE pull request #38
Opened 2020-11-27 15:18 UTC by SunnevaThorsteins

Users are now able to navigate WebRICE only using the keyboard in line with (accessibility guidelines)[https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211%2C214#keyboard-accessible]. All event listeners are an alternative for a 'click' event. With this, we have no key combination which automatically selects WebRICE. It is unnecessary to be in line with AA accessibility but we may wish to add it for user convenience later.

2020-11-27 17:45 UTC, judyfong requested changes

2020-11-27 17:45 UTC, judyfong commented on src/modules/SpeedButton.ts
> -    hideSpeedModule = this.closeUnusedSpeedComponents.bind(this);
removing this and binding directly in the eventlistener reintroduces the run away eventlistener bug again fixed by #29

2020-11-27 17:45 UTC, judyfong commented on src/modules/SpeedButton.ts
> +          this.keyboardCloseUnused(e);
this should probably be done a different way

2020-11-27 17:51 UTC, judyfong commented on src/modules/SpeedButton.ts
> +            this.closeUnusedSpeedComponents.bind(this));
this should probably be done a different way

2020-11-27 21:18 UTC, judyfong commented
It looks good. There's just the problem of the many eventlisteners.

2020-12-15 13:58 UTC, SunnevaThorsteins commented
Fixed the many event listeners bug I recreated so it should be set to merge

2020-12-15 16:46 UTC, judyfong commented on src/modules/SpeedButton.ts
> +            this.closeUnusedSpeedComponents.bind(this.hideSpeedModule));
```suggestion
            this.hideSpeedModule);
```

2020-12-15 16:47 UTC, judyfong commented on src/modules/SpeedButton.ts
> +          this.closeUnusedSpeedComponents.bind(this));
```suggestion
          this.hideSpeedModule);
```

2020-12-15 16:48 UTC, judyfong reviewed
I think there was a bit of confusion about the specific variable. So now I've added specific line suggestions.

2020-12-16 09:25 UTC, SunnevaThorsteins commented
Suggestions have been committed :)

2020-12-16 09:31 UTC, judyfong approved these changes

2020-12-16 09:31 UTC, merged