Add nav bar
cadia-lvl/WebRICE pull request #44
Opened 2021-02-16 12:08 UTC by djangoprince

2021-02-16 15:32 UTC, judyfong requested changes
This is a good start, Safa. However, some changes need to be made.

Here are changes we haven't discussed:
1. Add some space between WebRICE and the navbar. it doesn't look to have them right next to each other with no margins. I believe adding **margin: 0.5rem;** to the WebRICE_styles.css should be enough.
2. Solskin/Demo 2 should not open in a new browser tab but the same one so no **target=_blank**

As we've discussed, some changes need to be made
1. The Navbar needs to work in mobile. That seems to be a problem with the bootstrap css and the js having different version numbers (3.4.1 vs. 4.3.1). I believe **4.3.1** would be the version to use. No need to add popper.js.
2. The current page/link in the navbar should be white. This can be achieved by adding the **active** class to it. The rest can be muted or grayish.
3. The navbar should exist on all the demo pages.

I believe we've already made the following changes, they just need to be pushed:
1. Add the following text to the navbar: WebRICE, Dæmi 1, and Dæmi 2
2. Use relative links instead of absolute paths so it'll work in the development environment too.

Let me know if anything is unclear or if you encounter any problems.

2021-02-16 15:32 UTC, judyfong commented on build/index.html
> +
Whats left of this code should go in the head tag, under the other link tags, like it could go under line 19 favicon.ico

2021-02-16 15:32 UTC, judyfong commented on build/index.html
> +<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
```suggestion
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
```

2021-02-17 13:45 UTC, djangoprince commented
Changes 17/02

2021-02-17 14:19 UTC, judyfong approved these changes
Looks great. Good work.

2021-02-17 14:19 UTC, merged